name: Build for Linux with musl libc
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-musl-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the binary
        uses: ./actions/linux-musl
      - name: Upload react-x86_64-unknown-linux-musl.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-unknown-linux-musl.tar.gz
          path: target/release/react-x86_64-unknown-linux-musl.tar.gz
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/react-x86_64-unknown-linux-musl.tar.gz
          token: ${{ secrets.GH_TOKEN }}
