name: Build for Linux
on:
  release:
    types: [published]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
      - name: Build the binary
        run: |
          cargo build --release -vv
          mv target/release/react target/release/react_linux-x86_64
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-cli
          path: target/release/react_linux-x86_64
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/react_linux-x86_64
          token: ${{ secrets.GH_TOKEN }}
