name: Build for GNU/Linux
on:
  release:
    types: [published]
jobs:
  build-gnu-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
          target: i686-unknown-linux-gnu
      - name: Build the binary
        run: |
          rustup target add aarch64-unknown-linux-gnu
          sudo apt update && sudo apt install -y -qq gcc-i686-linux-gnu gcc-aarch64-linux-gnu
          mkdir -p .cargo

          echo '[target.i686-unknown-linux-gnu]'>>.cargo/config
          echo 'linker = "i686-linux-gnu-gcc"'>>.cargo/config

          echo '[target.aarch64-unknown-linux-gnu]'>>.cargo/config
          echo 'linker = "aarch64-linux-gnu-gcc"'>>.cargo/config

          cargo build -Zmultitarget --target=x86_64-unknown-linux-gnu --target=i686-unknown-linux-gnu --target=aarch64-unknown-linux-gnu --release -vv

          cd target/x86_64-unknown-linux-gnu/release/ && tar -cvf react-x86_64-unknown-linux-gnu.tar.gz react && cd ../..
          cd target/aarch64-unknown-linux-gnu/release/ && tar -cvf react-aarch64-unknown-linux-gnu.tar.gz react  && cd ../..
          cd target/i686-unknown-linux-gnu/release/ && tar -cvf react-i686-unknown-linux-gnu.tar.gz react  && cd ../..
      - name: Upload react-x86_64-unknown-linux-gnu.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-unknown-linux-gnu.tar.gz
          path: target/x86_64-unknown-linux-gnu/release/react-x86_64-unknown-linux-gnu.tar.gz
      - name: Upload aarch64-unknown-linux-gnu.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-aarch64-unknown-linux-gnu.tar.gz
          path: target/aarch64-unknown-linux-gnu/release/react-aarch64-unknown-linux-gnu.tar.gz
      - name: Upload i686-unknown-linux-gnu.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-i686-unknown-linux-gnu.tar.gz
          path: target/i686-unknown-linux-gnu/release/react-i686-unknown-linux-gnu.tar.gz
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/react-x86_64-unknown-linux-gnu.tar.gz
            target/i686-unknown-linux-gnu/release/react-i686-unknown-linux-gnu.tar.gz
            target/aarch64-unknown-linux-gnu/release/react-aarch64-unknown-linux-gnu.tar.gz
          token: ${{ secrets.GH_TOKEN }}
