name: Build for Linux with musl libc
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-musl-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the binary
        uses: ./actions/linux-musl
      - name: Upload react-x86_64-unknown-linux-musl.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-unknown-linux-musl.tar.gz
          path: target/x86_64-unknown-linux-musl/release/react-x86_64-unknown-linux-musl.tar.gz
      - name: Upload aarch64-unknown-linux-musl.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-aarch64-unknown-linux-musl.tar.gz
          path: target/aarch64-unknown-linux-musl/release/react-aarch64-unknown-linux-musl.tar.gz
      - name: Upload i686-unknown-linux-musl.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-i686-unknown-linux-musl.tar.gz
          path: target/i686-unknown-linux-musl/release/react-i686-unknown-linux-musl.tar.gz
      - name: Upload armv7-unknown-linux-musleabi.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-armv7-unknown-linux-musleabi.tar.gz
          path: target/armv7-unknown-linux-musleabi/release/react-armv7-unknown-linux-musleabi.tar.gz
      - name: Upload armv7-unknown-linux-musleabihf.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-armv7-unknown-linux-musleabihf.tar.gz
          path: target/armv7-unknown-linux-musleabihf/release/react-armv7-unknown-linux-musleabihf.tar.gz
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/react-x86_64-unknown-linux-musl.tar.gz
            target/i686-unknown-linux-musl/release/react-i686-unknown-linux-musl.tar.gz
            target/aarch64-unknown-linux-musl/release/react-aarch64-unknown-linux-musl.tar.gz
            target/armv7-unknown-linux-musleabi/release/react-armv7-unknown-linux-musleabi.tar.gz
            target/armv7-unknown-linux-musleabihf/release/react-armv7-unknown-linux-musleabihf.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
