name: Build for macOS
on:
  release:
    types: [published]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: stable
          target: "aarch64-apple-darwin"
      - name: Build the binary
        run: cargo build --release -vv
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-cli
          path: target/release/react
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/react
          token: ${{ secrets.GH_TOKEN }}
