name: Build for macOS
on:
  release:
    types: [published]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
          target: "aarch64-apple-darwin"
      - name: Build the binary
        run: |
          cargo build --release -Zmultitarget --target=x86_64-apple-darwin --target=aarch64-apple-darwin -vv
          cd target/x86_64-apple-darwin/release/ && tar -cvf react-x86_64-apple-darwin.tar.gz react  && cd ../..
          cd target/aarch64-apple-darwin/release/ && tar -cvf react-aarch64-apple-darwin.tar.gz react  && cd ../..
      - name: Upload react-x86_64-apple-darwin.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-apple-darwin.tar.gz
          path: target/x86_64-apple-darwin/release/react-x86_64-apple-darwin.tar.gz
      - name: Upload aarch64-apple-darwin.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-apple-darwin.tar.gz
          path: target/x86_64-apple-darwin/release/react-x86_64-apple-darwin.tar.gz

      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-apple-darwin/release/react-x86_64-apple-darwin.tar.gz
            target/aarch64-apple-darwin/release/react-aarch64-apple-darwin.tar.gz
          token: ${{ secrets.GH_TOKEN }}
