name: Build for macOS
on:
  release:
    types: [published]
jobs:
  build-linux:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          default: true
          toolchain: stable-macos
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
      - name: Build the binary
        run: cargo build --release -vv
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-cli
          path: target/release/react