name: Build for Windows
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
          target: "i686-pc-windows-msvc"
      - name: Build the binary
        run: |
          cargo build -Zmultitarget --target=x86_64-pc-windows-msvc --target=i686-pc-windows-msvc --release -vv
          cd target\x86_64-pc-windows-msvc\release && tar -cvf react-x86_64-pc-windows-msvc.zip react.exe  && cd ../../..
          cd target\i686-pc-windows-msvc\release && tar -cvf react-i686-pc-windows-msvc.zip react.exe  && cd ../../..
      - name: Upload react-x86_64-pc-windows-msvc
        uses: actions/upload-artifact@v3
        with:
          name: react-x86_64-pc-windows-msvc.zip
          path: target\x86_64-pc-windows-msvc\release\react-x86_64-pc-windows-msvc.zip
      - name: Upload react-i686-pc-windows-msvc
        uses: actions/upload-artifact@v3
        with:
          name: react-i686-pc-windows-msvc.zip
          path: target\i686-pc-windows-msvc\release\react-i686-pc-windows-msvc.zip

      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target\x86_64-pc-windows-msvc\release\react-x86_64-pc-windows-msvc.zip
            target\i686-pc-windows-msvc\release\react-i686-pc-windows-msvc.zip
          token: ${{ secrets.GH_TOKEN }}
