name: Build for Windows
on:
  release:
    types: [published]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
          target: "i686-pc-windows-msvc"
      - name: Build the binary
        run: |
          cargo build -Zmultitarget --target=x86_64-pc-windows-msvc --target=i686-pc-windows-msvc --release -vv
          ren target/x86_64-pc-windows-msvc/release/react target/x86_64-pc-windows-msvc/release/react-x86_64-pc-windows-msvc
          ren target/i686-pc-windows-msvc/release/react target/x86_64-pc-windows-msvc/release/react-i686-pc-windows-msvc
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-cli
          path: |
            target/x86_64-pc-windows-msvc/release/react-x86_64-pc-windows-msvc
            target/x86_64-pc-windows-msvc/release/react-i686-pc-windows-msvc
      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/react-x86_64-pc-windows-msvc
            target/x86_64-pc-windows-msvc/release/react-i686-pc-windows-msvc
          token: ${{ secrets.GH_TOKEN }}
